### ISSUE TITLE
Please Help. Not working for me

### ISSUE THREAD

**Issue by makpapad** [opsway/magento2-module-amazonses#1]
Hello. 
I install the module in magento 2.1.2. I create in Amazon IAM user with AmazonSESFullAccess permission, I fill the required inputs in module and testing emails but when I press SEND button nothing happen, 
What I'm doing wrong?

**Comment by slimzc** [comment]
I have the same problem. When I press send only return "null" in the response.

**Comment by dmitrijivanenko** [comment]
Thank you for your report, actualy we did not tested on 2.1.2 vesrion. Will check soon.

**Comment by trebb0r** [comment]
I also have this problem with Magento version 2.1.1 (return "null" in the response).

**Comment by dmitrijivanenko** [comment]
Thank you for your feedback, you problem is in Amazon SES credentials. 

Before AWS had default host with wich you could work, now it asks direct host wich is set in your settings (check AWS settings in order to get your account correct host). 

By default module uses https://email.us-west-2.amazonaws.com , with ( https://github.com/opsway/magento2-module-amazonses/commit/51497e5fec2bed9751b0d426d86e01e38ce6ce50 ) it is added a new setting in dashboard - **host**, where you can change it. 

Always check if your adress which are you trying to send your emails is verifed

**Dont forget to save your changes before sending test message**
